export const destinationArr = [
  { speciesID: 9606, ncibName: 'Homo sapiens', chineseName: '智人'},
  { speciesID: 10090, ncibName: 'Mus musculus', chineseName: '小鼠' },
  { speciesID: 9913, ncibName: 'Bos taurus', chineseName: '牛' },
  { speciesID: 10116, ncibName: 'Rattus norvegicus', chineseName: '褐家鼠' },
  { speciesID: 9615, ncibName: 'Canis lupus familiaris', chineseName: '家犬' },
  { speciesID: 9823, ncibName: 'Sus scrofa', chineseName: '欧亚野猪' },
  { speciesID: 7955, ncibName: 'Danio rerio', chineseName: '斑马鱼' },
  { speciesID: 8364, ncibName: 'Xenopus (Silurana) tropicalis', chineseName: '非洲爪蟾' },
  { speciesID: 59729, ncibName: 'Taeniopygia guttata', chineseName: '斑胸草雀' },
  { speciesID: 3702, ncibName: 'Arabidopsis thaliana', chineseName: '拟南芥' },
  { speciesID: 4932, ncibName: 'Saccharomyces cerevisiae', chineseName: '酿酒酵母' },
  { speciesID: 7227, ncibName: 'Drosophila melanogaster', chineseName: '黑腹果蝇' },
  { speciesID: 9031, ncibName: 'Gallus gallus', chineseName: '原鸡' },
  { speciesID: 3847, ncibName: 'Glycine max', chineseName: '大豆' },
  { speciesID: 3694, ncibName: 'Populus trichocarpa', chineseName: '毛果杨' },
  { speciesID: 59689, ncibName: 'Arabidopsis lyrata', chineseName: '琴叶拟南芥' },
  { speciesID: 9796, ncibName: 'Equus caballus', chineseName: '马' },
  { speciesID: 39947, ncibName: 'Oryza sativa Japonica Group', chineseName: '粳稻' },
  { speciesID: 9685, ncibName: 'Felis catus', chineseName: '家猫' },
  { speciesID: 6239, ncibName: 'Caenorhabditis elegans', chineseName: '秀丽隐杆线虫' },
  { speciesID: 9646, ncibName: 'Ailuropoda melanoleuca', chineseName: '大熊猫' },
];
